### ISSUE TITLE
XML Layout for Leave Form Activity

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#10]
Create the XML layout for Leave Form Activity based on the design provided in the [Figma](https://www.figma.com/design/jYm7XGidk1L3HNf9e4Otwn/myLeave?node-id=6-18&t=HjrOtyAfoLbxQDPn-1).

Your layout must follow these guidelines:

1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
2. Use Scroll View to add scrolling feature in the form.
3. Adhere to the given Figma design
4. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by AyushNarsian** [comment]
Good evening maintainer @Agrim2112  
I would like to work on this issue. I will follow all the guidelines and use constraint layout and in it i will use scroll view. I will make the page responsive to all screen sizes. I will also define all the colors in colors xml file before using them and design the page exactly like the figma provided. I will also give sensible id names to provide clarity and consistency.

**Comment by Agrim2112** [comment]
@AyushNarsian You can work on it
