### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#12]
1.  Make the design consistent for Sign Up and Login Activity as given in the Figma deign . Test the design on physical device and make the UI changes accordingly, add appropriate layout margins in the multiples of 4 and increase the text sizes. 

Current design on physical device: 

<img src="https://github.com/bsoc-bitbyte/myLeave/assets/128930038/92b701ad-d014-4a39-a42d-a4b7d83c2cb0" width="20%" height="20%">

<img src="https://github.com/bsoc-bitbyte/myLeave/assets/128930038/19834f75-ab24-48b6-93a6-204978638162" width="20%" height="20%" >

2. Fix the background colour issue and also wrap the root Relative Layout with a Constraint Layout in Login Activity.
3. Apply all the correct font families in all activities as per the Figma design.

**Comment by AyushNarsian** [comment]
Good afternoon maintainer @Agrim2112 !
I would like to work on the issue as I've examined the code and I can make the required changes and solve the bug. There are also colors used in the file without declaring in colors xml file first. I would resolve that too.

**Comment by zephyr004** [comment]
Maintainer @Agrim2112 ,
I would like to work on this issue which requires UI fixes. I'll be following the required guidelines, the Figma design and adjust the XML files accordingly. I'll ensure that the layout structure and design elements are consistent between both activities. I'll modify the margins and text sizes, include new fonts, set a consistent background color for both activities and update the root layout from RelativeLayout to ConstraintLayout
Thankyou.

**Comment by Agrim2112** [comment]
@zephyr004 Go ahead
