### ISSUE TITLE
Implement View Binding

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#13]
Implement View Binding in all the activities. The build feature has already been added in the Gradle file, so just declare the binding variable in each activity and set its root.

**Comment by aniket0742** [comment]
@Agrim2112 I would like to work on this issue, I'll declare a variable for binding object and initialize the binding variable and use the setContentView method with root view of the binding object.

**Comment by Agrim2112** [comment]
@aniket0742 You can work on this. Make changes using binding wherever findViewbyId has been used.
