### ISSUE TITLE
XML Layout for Leave History Activity

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#15]
Create the XML layout for Leave History Activity based on the design provided in the [Figma](https://www.figma.com/design/jYm7XGidk1L3HNf9e4Otwn/myLeave?node-id=6-18&t=HjrOtyAfoLbxQDPn-1).

Your layout must follow these guidelines:

1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
2. Use Nested Scroll View to add scrolling.
3. No need to create Recycler View layout and adapter, just add an empty Recycler View.
4. Adhere to the given Figma design.
5. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by AyushNarsian** [comment]
Good evening maintainer @Agrim2112 ! I would like to work on this issue. My approach would match the instructions given by you and I'll use constraint layout with nested scroll view and I'll add an empty recycler view and the fonts,colors,margins and padding according to the figma wherever required. The naming convention will also be followed while naming the ids and i'll also add comments to make the code review easier

**Comment by ayushsaksena30** [comment]
@Agrim2112 I would like to work on this issue. My approach will be to use two buttons to display back and leaves. I will also use Nested Scroll View to display the list. Inside it, i'll declare an empty recycler view. I'll wrap everything in constraint layout to ensure responsiveness of screen and will follow the font family, margins and naming conventions from the given Figma file.
Thank You

**Comment by aniket0742** [comment]
@Agrim2112 Sir, I would like to work on this issue. I will use ConstraintLayout as the root layout to ensure responsiveness across different screen sizes. Inside it I will add a Nested ScrollView for scrolling. within the scroll view I will place another Constraintlayout to organize the content and add empty recycler view. I will add the necessary constraints and styles according to the Figma design following the naming conventions. 
Thank You.

**Comment by sujalagrawal2** [comment]
@Agrim2112 I would like to work on this issue. I will use ConstraintLayout and inside it I will add nestedScrollView. I will also add empty recycler view. I will use two customized button according to the figma. I will give proper margins and proper naming convention for each ID.
Thank You.

**Comment by Agrim2112** [comment]
@AyushNarsian You can work on it.
