### ISSUE TITLE
XML Layout for Leave Request Activity

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#17]
Create the XML layout for Leave Request Activity based on the design provided in the [Figma](https://www.figma.com/design/jYm7XGidk1L3HNf9e4Otwn/myLeave?node-id=6-18&t=HjrOtyAfoLbxQDPn-1).

Your layout must follow these guidelines:

1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
2. Use Scroll View to add scrolling.
4. Adhere to the given Figma design.
5. Follow the specified naming convention for each view group ID to maintain consistency and clarity

**Comment by ayushsaksena30** [comment]
@Agrim2112 I would like to work on this issue. My approach will be to use CardView and inside it, I'll use constraint layout to display Headers and use Linear Layout to display subsections for Details and Leave. I'll use textView and imageView to display purpose and attachment and use two buttons. 
I'll wrap everything up with Scroll View and maintain the margins and follow the naming conventions and styles from Figma provided.
Thank You

**Comment by sujalagrawal2** [comment]
@Agrim2112 I would like to work on this issue. My approach for this layout will be constraintLayout  -> CardView -> NestedScrollView -> Constraint.  Inside Constraint Layout  I will use TextView, EditText, ImageView(for back and download icon) , guideline (in details section ) , linear layout( in LEAVE ) and  Button. I will provide proper margins according to figma and follow proper naming conventions for the ID.
Thank You.

**Comment by Agrim2112** [comment]
@sujalagrawal2 You can work on it
