### ISSUE TITLE
Implement Date Picker in Leave Form Activity

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#19]
Integrate a Date Picker into the Leave Form Activity that activates when the user selects the leave date field. Ensure that the Date Picker allows users to choose dates starting from today onward and update the field value when the user selects a date.

**Comment by ayushsaksena30** [comment]
@Agrim2112 I would like to work on this issue.
My approach will be to use setOnClickListener for Leave button to open DatePickerDialog and display the updated selected date in the format dd/mm/yyyy.
Thank You

**Comment by AyushNarsian** [comment]
Good evening maintainer @Agrim2112 . I would like to work on this issue. In my approach I will make the date textbox non editable to ensure that the user will select the date only from date picker. I'll initialize the date picker dialog with the current date and restrict it to dates from today onwards. I'll  set an on click listener on the edit text to display the date picker dialog when the field is clicked.

**Comment by Agrim2112** [comment]
@ayushsaksena30 Go ahead
