### ISSUE TITLE
XML Layout for custom Dialog Box

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#23]
Create the XML layout for custom Dialog Box based on the design provided in the [Figma](https://www.figma.com/design/jYm7XGidk1L3HNf9e4Otwn/myLeave?node-id=6-18&t=HjrOtyAfoLbxQDPn-1) . Since the layout for both dialog boxes is the same, you can reuse the code

Your layout must follow these guidelines:

1. Use Linear Layout to create the custom Dialog Box .
1. Adhere to the given Figma design
1. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by madhavs004** [comment]
@Agrim2112 I would like to work on this issue. I will use Linear layout vertically to create the dialog box and I will use chain to constrain the buttons. I will also use the specified naming convention for the textviews. Please assign me this issue. Thanks.

**Comment by sujalagrawal2** [comment]
@Agrim2112 I would like to work on this issue. I will use Linear layout vertically for two TextView and for button I will use Linear Layout horizontally with layout_weight property. I will properly use margin (as shown in figma ) and follow specified naming convention for each view group ID.
Thank You.

**Comment by Agrim2112** [comment]
@madhavs004 You can take up the issue
