### ISSUE TITLE
Implement Image Picker in Leave Form Activity 

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#25]
Integrate a Image Picker into the Leave Form Activity that allows users to select images and PDFs. You can use Intent class to open file picker and specify the types of files you want to pick.

**Comment by ayushsaksena30** [comment]
@Agrim2112 I would like to work on the issue.
My approach will be to take permission to read external storage from android manifest file and implement a function to open the file picker based on the option selected by user for image or pdf upload and then display the file name in Attachment text view.
Thank you

**Comment by Agrim2112** [comment]
@sujalagrawal2 You can work on it
