### ISSUE TITLE
XML layout for Forgot Password Activity

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#27]
Create the XML layout for Forgot Password Activity based on the design provided in the [Figma](https://www.figma.com/design/jYm7XGidk1L3HNf9e4Otwn/myLeave?node-id=6-18&t=HjrOtyAfoLbxQDPn-1).

Your layout must follow these guidelines:

1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
2. Try to maintain uniformity with the Sign Up and Login page, you can reuse the code.
3. Adhere to the given Figma design
4. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by aniket0742** [comment]
@Agrim2112 I want to work on this issue, I'll reuse the code to ensure it remains same and uniform as Login and SignUp page. Also I'm going to use Constraint Layout to bind all the elements and ensure it remains responsive to all screen sizes and will strictly follow the design provided in the Figma file.

**Comment by AyushNarsian** [comment]
Good evening @Agrim2112 
I would like to work on this issue. I will take reference from the sign up and login activity XML code and will use constraint layout for better screen responsiveness and will strictly use naming convention for labelling ids.
Thank you!

**Comment by Agrim2112** [comment]
@aniket0742 Go ahead

**Comment by Agrim2112** [comment]
@aniket0742 Any updates on the issue?

**Comment by aniket0742** [comment]
@Agrim2112  got delayed because of some issue with my system, I will be submitting the pull request tonight by 10pm.
