### ISSUE TITLE
 Implement Email Validation and Sign-Up Response Handling

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#29]
- Add an intent to navigate to the `LoginActivity` when the login text is clicked.

- Implement email validators to:
  - Check if the email field contains a valid email address.
  - Ensure the email domain is `@iiitdmj.ac.in` using regex.

- Handle sign-up responses:
  - Display a loading animation when the sign-up process is in progress.
  - On successful sign-up, navigate to the User Dashboard and remove all previous activities from the backstack.
  - Show a toast message for any empty or error states during sign-up.

**Comment by AyushNarsian** [comment]
Good afternoon @Agrim2112 !!
I would like to work on this issue. My approach includes adding an onclicklistener on loginactivity also use email validators using regex to check if the email is valid. I will implement a loading animation while the sign up process is in progress. On successful sign-up, I will navigate to the User Dashboard with flags to clear the backstack. I will also display toast messages for any empty or error states during sign up. I would like to work on this issue as I will learn a lot from the process.

**Comment by ayushsaksena30** [comment]
@Agrim2112 I would like to work on this issue.
My approach will be to use onclicklistener for login button. I will use Patterns.EMAIL_ADDRESS to check for valid email and use regex to check for domain. I will implement a progress bar to show loading animation by toggling its visibility as true when sign up button is clicked. I will use intent flags to remove all previous activities. I will also handle all error messages and toast appropriate error messages.
Please Assign this issue to me.
Thank You

**Comment by zephyr004** [comment]
Good afternoon @Agrim2112,

I am interested in working on the issue related to email validation and sign-up response handling. My approach includes adding an OnClickListener for the login text to direct users to the Loginactivity. For email validation, I will use Patterns.EMAIL_ADDRESS to verify the correct email format and a regex pattern to ensure the domain is @iiitdmj.ac.in. During the sign-up process, I will introduce a progress bar to display a loading animation. Upon successful sign-up I will navigate users to the User Dashboard and use intent flags to clear the backstack providing a smooth user experience. Additionally, I will display appropriate toast messages for any empty fields or errors during the sign-up.
Thank you..

**Comment by Agrim2112** [comment]
@ayushsaksena30 You can work on it.
