### ISSUE TITLE
XML Layout for Login Activity

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#3]
Create the XML layout for Login Activity based on the design provided in the [Figma](https://www.figma.com/design/jYm7XGidk1L3HNf9e4Otwn/myLeave?node-id=6-18&t=HjrOtyAfoLbxQDPn-1).

Your layout must follow these guidelines:

1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
2. Adhere to the given Figma design
3. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by ritankarsaha** [comment]
I would like to work on this issue ensuring that all layouts use ConstraintLayout to manage the responsive behaviour more effectively and adjust the constraints of each view to ensure they display properly across different screen sizes following the figma design. 
Please assign me this issue under BSoC'24. Thank You.

**Comment by madhavs004** [comment]
@Agrim2112 I would like to work on this issue. 
I will be using Textviews and Edittexts with hints to input the email and password. I would use imageview to display the background image.
Thanks.

**Comment by Agrim2112** [comment]
@ritankarsaha you can work on this

**Comment by ritankarsaha** [comment]
@Agrim2112 Can you pls provide the background image to be added the res folder? or should i just screenshot it out from the figma file?

**Comment by ritankarsaha** [comment]
@Agrim2112  I have fixed the issue #3 and also opened a PR for the same #5.
