### ISSUE TITLE
Implement Login Response Handling

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#30]
- Add an intent to navigate to the `SignUpActivity` when the sign up text is clicked.

- Handle login responses:
  - Display a loading animation when the login process is in progress.
   - On successful login, navigate to the appropriate dashboard based on the user role, User Dashboard for regular users and Admin Dashboard for admin users.
  - Ensure all previous activities are removed from the backstack during navigation.
  - Show a toast message for any empty or error states during login.

**Comment by ayushsaksena30** [comment]
@Agrim2112 I would like to work on this issue.
My approach will be to use onclicklistener when sign up text is clicked.I will make a function to navigate admin to admin dashboard and user to user dashboard. I will also implement a progress bar to show loading animation by toggling its visibility as true when sign up button is clicked. I will use intent flags to remove all previous activities. I will also handle all error messages and toast appropriate error messages.
Please Assign this issue to me.
Thank You

**Comment by madhavs004** [comment]
I would like to work on this issue. 
I will use onclicklistener to start SignUpActivity with intent. I will implement a progress bar animation between the loading time of the activities. I will use conditional logic to start the different dashboards by validating the user email address. To clear the previous activities , i will use clear_task flag while moving to the new activity. I will use appropriate toasts to show the empty/invalid response messages and other error messages. 
Thanks.

**Comment by sujalagrawal2** [comment]
@Agrim2112 I would like to work on this issue.
My approach will be:
i) Use onClickLishner on signUp text when it is clicked and using explicit intent I will navigate to SignUp Activity.
ii) In the code provided ( Resource.Status.LOADING -> {}) I will implement a progressDialog and I will close it when the loading is success
iii) To check whether the user is regular or admin I will check if (it.data?.isAdmin) is true or not in the provided code (Resource.Status.SUCCESS -> {}). According to the result I will navigate.
iv) To remove all the activities from backstack I will use intent flags (FLAG_ACTIVITY_CLEAR_TASK). 
v) I will show toast message in  Resource.Status.ERROR -> {}  and Resource.Status.EMPTY -> {}
