### ISSUE TITLE
XML Layout for Recycler View Item in User and Admin Dashboard

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#8]
Create the XML layout for User Dashboard and Admin Dashboard based on the design provided in the [Figma](https://www.figma.com/design/jYm7XGidk1L3HNf9e4Otwn/myLeave?node-id=6-18&t=HjrOtyAfoLbxQDPn-1). 

Your layout must follow these guidelines:

1. Use Linear Layout to create the Recycler View item, no need to create the adapter .
4. Adhere to the given Figma design
5. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by sujalagrawal2** [comment]
@Agrim2112 I would like to work on it. My approach is to make linear layout(orientation = vertical) and inside it I will place three TextView and for middle TextView I will use (layout_gravity=end). I will follow the specified naming convention for each ID.
Thank You.

**Comment by ayushsaksena30** [comment]
@Agrim2112 I would like to work on this issue. My approach will be to use Card View to display rounded corners with margins from the edges and use padding inside the layout. I'll also use Constraint Layout with proper margins to display the three Text Views to make the screen more responsive.
I'll also follow the UI styles and naming conventions from the Figma provided.
Thank You

**Comment by Agrim2112** [comment]
@sujalagrawal2 You can work on it. You would need to use 2 Linear layouts nested in a Linear layout (orientation=horizontal). You can use a Card View to give rounded corners.

**Comment by Agrim2112** [comment]
@ayushsaksena30 You can take up the issue. Use nested Linear layouts within a Linear layout to make the Recycle View item.
